update=Mon 11 Aug 2014 04:22:29 PM EDT
last_client=cvpcb
[pcbnew]
[pcbnew/libraries]
LibName1=sockets
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=smd_capacitors
LibName7=smd_resistors
LibName8=smd_crystal&oscillator
LibName9=smd_transistors
LibName10=libcms
LibName11=display
LibName12=led
LibName13=dip_sockets
LibName14=pga_sockets
LibName15=valves
LibDir=modules
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
